# Generated by Django 2.2 on 2019-04-09 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('equipmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('serial_num', models.IntegerField()),
                ('license_num', models.IntegerField()),
                ('operator', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='fireincident',
            fields=[
                ('incidentid', models.IntegerField(primary_key=True, serialize=False)),
                ('incident_name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'fireincident',
            },
        ),
        migrations.CreateModel(
            name='orderingoffice',
            fields=[
                ('orderingofficeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('zip_code', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'orderingoffice',
            },
        ),
        migrations.CreateModel(
            name='hiring_ticket',
            fields=[
                ('ticketid', models.IntegerField(primary_key=True, serialize=False)),
                ('use_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.DateField(default=datetime.date.today)),
                ('end_time', models.DateField(default=datetime.date.today)),
                ('assignment', models.CharField(max_length=200)),
                ('comments', models.CharField(default='comments', max_length=200)),
                ('repname', models.CharField(default='repname', max_length=200)),
                ('repsign', models.CharField(default='signature', max_length=80)),
                ('vendorsign', models.CharField(default='signature', max_length=80)),
                ('sign_date', models.DateField(default=datetime.date.today)),
                ('equipmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring_ticket.equipment')),
                ('incidentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring_ticket.fireincident')),
            ],
            options={
                'db_table': 'hiring_ticket',
            },
        ),
        migrations.CreateModel(
            name='eeraagreement',
            fields=[
                ('eeraid', models.IntegerField(primary_key=True, serialize=False)),
                ('agreement_num', models.IntegerField()),
                ('begin_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('orderingofficeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring_ticket.orderingoffice')),
            ],
            options={
                'db_table': 'eeraagreement',
            },
        ),
    ]
