# Generated by Django 2.2 on 2019-04-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendorid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('zip_code', models.IntegerField()),
                ('phone1', models.CharField(max_length=14)),
                ('phone2', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Vendors',
                'db_table': 'vendor',
            },
        ),
        migrations.AlterModelOptions(
            name='eeraagreement',
            options={'verbose_name': 'Eeraagreements'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='fireincident',
            options={'verbose_name': 'Fire Incidents'},
        ),
        migrations.AlterModelOptions(
            name='hiring_ticket',
            options={'verbose_name': 'Hiring Tickets'},
        ),
        migrations.AlterModelOptions(
            name='orderingoffice',
            options={'verbose_name': 'Ordering Offices'},
        ),
        migrations.AlterField(
            model_name='eeraagreement',
            name='eeraid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fireincident',
            name='incidentid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hiring_ticket',
            name='ticketid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderingoffice',
            name='orderingofficeid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderingoffice',
            name='phone',
            field=models.CharField(max_length=14),
        ),
        migrations.AddField(
            model_name='eeraagreement',
            name='vendorid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hiring_ticket.vendor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='vendorid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hiring_ticket.vendor'),
        ),
        migrations.AddField(
            model_name='hiring_ticket',
            name='vendorid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hiring_ticket.vendor'),
        ),
    ]
